/// <reference path="engine.configProvider.js" />
/// <reference path="engine.configProvider.js" />
/// <reference path="components/jsonbasedpages/directive/menu/idsSideMenuDirective.js" />
var currentEngineName = renderingEngine;
var commonLibPath = "../common-lib/";
//var minified_suf
require({
    baseUrl: 'engines/' + currentEngineName + "/",
    urlArgs: 'v=' + version,
    waitSeconds: 0,
    // alias libraries paths.  Must set 'angular'
    paths: {
        'jQuery': commonLibPath + 'jquery.min',
        'jQuery-template': commonLibPath + 'jquery.tmpl.min',
        'moment': commonLibPath + 'moment',
        'daterangepicker': commonLibPath + 'bootstrap-daterangepicker',
        'selectize': commonLibPath + 'selectize',
        'underscore': commonLibPath + 'underscore-min',
        'platform-main-module': 'platform-main-module',
        'extension-module': 'extensions/extension-module',
        'alasql': commonLibPath + 'alasql/alasql',
        'alaSqlExtensions': 'extensions/alaSqlExtensions',
        //'handsontable': commonLibPath + 'handsontable/handsontable',
        //'pikaday': commonLibPath + 'handsontable/pikaday/pikaday',
        'numbro': commonLibPath + 'handsontable/numbro/numbro',
        //'zeroclipboard': commonLibPath + 'handsontable/zeroclipboard/zeroclipboard',
        'overlay': 'factories/overlay',
        'angular': 'lib/angular',
        'angular-route': 'lib/angular-route',
        'angular-ui-router': 'lib/angular-ui-router',
        'angularAMD': 'lib/angularAMD',
        'ngload': 'lib/ngload',
        'angular-resource': 'lib/angular-resource',
        'angular-touch': 'lib/angular-touch.min',
        'angular-carousel': 'lib/angular-carousel.min',
        'angular-selectize': 'lib/angular-selectize',
        'angular-ui-bootstrap': 'lib/angular-ui-bootstrap',
        'angular-ivh-treeview': 'lib/ivh-treeview.min',
        'angular-datepicker': 'lib/angular-datepicker',
        'angular-daterangepicker': 'lib/angular-daterangepicker',
        'ui-grid': 'lib/ui-grid',
        'ngdatepicker': 'lib/ngSimpleDatePicker',
        'ngmultiDatePicker': 'lib/multipleDatePicker',
        'ngtimepicker': 'lib/ez-timepicker.min',
        'angucomplete': 'lib/angucomplete',
        'angularCSS': 'lib/angular-css.min',
        /*'csvlib': 'lib/csv',
        'pdflib': 'lib/pdfmake',
        'vfsfonts': 'lib/vfs_fonts',*/
        'notify': 'lib/angular-notify',
        'angular-growl': 'lib/angular-growl.min',
        'angular-slimscroll': 'lib/angular-slimscroll',
        //'ui.bootstrap': 'lib/ui-bootstrap-tpls',
        "ngMaterial": "lib/angular-material.min",
        'ngMdIcons' : 'lib/angular-material-icons.min',
        "ngStorage": "lib/ngStorage.min",
        "ngHandsontable": "lib/ngHandsontable",
        'btorfs.multiselect': "lib/angular-bootstrap-multiselect",
        'angularjs-gauge':'lib/angularjs-gauge',
       // 'pdfjs':'lib/pdf',
        'pdfjsViewer': 'lib/angular-pdfjs-viewer',
        'selectjs': "lib/select",
        'dndLists':'lib/angular-drag-and-drop-lists',
        "DlhSoft":  "lib/DlhSoft",
        'ace':'lib/src-noconflict/ace',
        'ui-ace':'lib/angular-ui-ace/ui-ace.min',
        "ngSanitize": "lib/angular-sanitize",


        "angular-animate": "lib/angular-animate.min",
        "angular-aria": "lib/angular-aria.min",
        "angular-messages": "lib/angular-messages.min",
       

        'appDefinitionService': 'services/appDefinitionService',
        'menuDefinitionService': 'services/menuDefinitionService',
        'screenDefinitionService': 'services/ScreenDefinitionService',

        'stateService': 'services/stateService',
        'tenantService': 'services/tenantService',
        'utilService': 'services/utilService',
        'modelUtilService': 'services/modelUtilService',
        'dateUtilService': 'services/dateUtilService',
        'localPersistenceService': 'services/localPersistenceService',
        'engineConstants': 'engine.constants',
        'engine.configProvider': 'engine.configProvider',
        'httpService': 'services/httpService',
        'authService': 'services/authService',
        'modalPopUpService': 'services/modalPopUpService',

        'idsSideMenu': 'components/jsonbasedpages/directive/menu/idsSideMenuDirective',
        'IdsSideMenuCtrl': 'components/jsonbasedpages/directive/menu/idsSideMenuCtrl',
        'idsSideMenuService': 'components/jsonbasedpages/directive/menu/idsSideMenuService',
        'idsSideMenuHelpersDirective': 'components/jsonbasedpages/directive/menu/idsSideMenuHelpersDirective',

        'idsPanel.directive': 'directives/idsPanel/idsPanel.directive',
        'idsPanel.service': 'directives/idsPanel/idsPanel.service',
        'idsPanelBlur.directive': 'directives/idsPanel/idsPanelBlur.directive',
        'idsPanelBlurHelper.service': 'directives/idsPanel/idsPanelBlurHelper.service',
        'idsPanelSelf.directive': 'directives/idsPanel/idsPanelSelf.directive',


        // 'dateRangeService': 'services/dateRangeService',
        'registrationsDirective': 'components/jsonbasedpages/directive/registrations/registrationsDirective',
        'dynamicFormDirective': 'components/jsonbasedpages/directive/form/dynamicFormDirective',
        'sectionDirective': 'components/jsonbasedpages/directive/form/sectionDirective',
        'rowDivisionDirective': 'components/jsonbasedpages/directive/form/rowDivisionDirective',
        'fieldDirective': 'components/jsonbasedpages/directive/form/fieldDirective',
        'pageTop': 'directives/pageTop/pageTopDirective',
        'appToolbar': 'directives/appToolbar/appToolbarDirective',
        'actionsDirective': 'directives/actions/actionsDirective',
        'breadcrumbDirective': 'directives/breadcrumb/breadcrumbDirective',
        'nestedSelect': 'components/jsonbasedpages/directive/dropdown/nestedSelectDirective',
       // 'textBoxDirective': 'components/jsonbasedpages/directive/form/textBoxDirective',
    //    'dropDownDirective': 'components/jsonbasedpages/directive/form/dropDownDirective',

        'numericStepper': 'components/jsonbasedpages/directive/form/numericStepper',
        'fieldBaseController': 'components/jsonbasedpages/directive/form/controllers/fieldBaseController',
        'fieldDefaultController': 'components/jsonbasedpages/directive/form/controllers/fieldDefaultController',
        'dateRangeFieldController': 'components/jsonbasedpages/directive/form/controllers/dateRangeFieldController',
        'compositeRepeaterFieldController': 'components/jsonbasedpages/directive/form/controllers/compositeRepeaterFieldController',
        'gridFieldController': 'components/jsonbasedpages/directive/form/controllers/gridFieldController',
        'excelGridFieldController': 'components/jsonbasedpages/directive/form/controllers/excelGridFieldController',
        'raceDayFieldController': 'components/jsonbasedpages/directive/racing/raceDayFieldController',
        'fieldService': 'components/jsonbasedpages/directive/form/services/fieldService',
        'gridService': 'components/jsonbasedpages/directive/form/services/gridService',
        'InlineEdit': 'components/jsonbasedpages/directive/form/factories/uiGridInlineEditFactory',
        'requireJsProxyFactory': 'components/jsonbasedpages/directive/form/factories/requireJsProxyFactory',
        'attribute-level-field-directives': 'components/jsonbasedpages/directive/form/attribute-level-field-directives',
      //  'dropDownController': 'components/jsonbasedpages/directive/form/controllers/dropDownController',
        'gaugeController': 'components/jsonbasedpages/directive/form/controllers/gaugeController',
        'webPortalFieldController': 'lib/customfields/webportalField/webPortalFieldController',
        'aceController':'components/jsonbasedpages/directive/form/controllers/aceController',
        'kanbanController':'components/jsonbasedpages/directive/form/controllers/kanbanController',
        'genericController':'components/jsonbasedpages/directive/form/controllers/genericController',
        'progressstepsContrroller':'components/jsonbasedpages/directive/form/controllers/progressstepsContrroller',
    },
    // Add angular modules that does not support AMD out of the box, put it in a shim
    shim: {
        'daterangepicker': ['jQuery'],
        'jQuery-template': ['jQuery'],
        'moment': ['jQuery'],
        'selectize': ['jQuery'],
        'angular': ['jQuery'],
        'angular-route': ['angular'],
        'angular-ui-router': ['angular'],
        'angularAMD': ['angular'],
        'ngload': ['angularAMD'],
        'angular-resource': ['angular'],
        'angular-touch': ['angular'],
        'angularCSS': ['angular'],
        'angular-carousel': ['angular-touch'],
        'angular-selectize': ['angular', 'selectize'],
        'angular-ui-bootstrap': ['angular'],
        'angular-ivh-treeview': ['angular'],
        'angular-datepicker': ['angular'],
        'angular-daterangepicker': ['angular'],
        'ui-grid': ['angular'],
        'ngdatepicker': ['angular'],
        'ngmultiDatePicker': ['angular'],
        'ngtimepicker': ['angular'],
        'angucomplete': ['angular'],
        'notify': ['angular'],
        'angular-growl': ['angular'],
        'angular-slimscroll': ['angular'],
        'ngStorage': ['angular'],
        'btorfs.multiselect': ['angular'],
        'angularjs-gauge': ['angular'],
        'pdfjsViewer': ['angular'],
        'handsontable': ['moment', 'pikaday', 'numbro','zeroclipboard'],
        'ngHandsontable': ['angular'],
        'ngSanitize': ['angular'],
        'ngMdIcons':['angular'],

        'angular-animate': ['angular'],
        'angular-aria': ['angular'],
        'angular-messages': ['angular'],
        "ngMaterial": ['angular', 'angular-animate', 'angular-aria', 'angular-messages'],
     
        /*'csvlib':['angular'],
        'pdflib':['angular'],
        'vfsfonts':['pdflib']*/

        'appDefinitionService': ['angularAMD'],
        'menuDefinitionService': ['angularAMD'],
        'screenDefinitionService': ['angularAMD'],

        'stateService': ['angularAMD'],
        'tenantService': ['angularAMD'],
        'utilService': ['angularAMD'],
        'modelUtilService': ['angularAMD'],
        'dateUtilService': ['angularAMD'],
        'localPersistenceService': ['angularAMD'],
        'registrationsDirective': ['angularAMD'],
        'httpService': ['angularAMD'],
        'authService': ['angularAMD'],
        'modalPopUpService':['angularAMD'],

        'idsSideMenu': ['angularAMD'],
        'IdsSideMenuCtrl': ['angularAMD'],
        'idsSideMenuService': ['angularAMD'],
        'idsSideMenuHelpersDirective': ['angularAMD'],

        'engineConstants': ['angularAMD'],
        'engine.configProvider': ['angularAMD'],

        //'ui.bootstrap': ['angularAMD'],
    //    'dropDownDirective': ['angularAMD'],
    //    'textBoxDirective': ['angularAMD'],
        'dynamicFormDirective': ['angularAMD'],
        'sectionDirective': ['angularAMD'],
        'rowDivisionDirective': ['angularAMD'],
        'fieldDirective': ['angularAMD'],
        'pageTopDirective': ['angularAMD'],
        'appToolbar': ['angularAMD'],
        'actionsDirective': ['angularAMD'],
        'breadcrumbDirective': ['angularAMD'],
        'dropdownDirective': ['angularAMD'],

        'idsPanel.directive': ['angularAMD'],
        'idsPanel.service': ['angularAMD'],
        'idsPanelBlur.directive': ['angularAMD'],
        'idsPanelBlurHelper.service': ['angularAMD'],
        'idsPanelSelf.directive': ['angularAMD'],

        'numericStepper': ['angularAMD'],
        'fieldBaseController': ['angularAMD'],
        'fieldDefaultController': ['angularAMD'],
        'dateRangeFieldController': ['angularAMD'],
        'compositeRepeaterFieldController': ['angularAMD'],
    //    'dropDownController': ['angularAMD'],
        'gaugeController': ['angularAMD'],
        'aceController': ['angularAMD'],
        'kanbanController': ['angularAMD'],
        'genericController': ['angularAMD'],
        'progressstepsContrroller':['angularAMD'],

        'gridFieldController': ['angularAMD'],
        'excelGridFieldController': ['angularAMD'],
        'raceDayFieldController': ['angularAMD'],
        'webPortalFieldController': ['angularAMD'],
        'fieldService': ['angularAMD'],
        'gridService': ['angularAMD'],
        'InlineEdit': ['angularAMD'],
        'requireJsProxyFactory': ['angularAMD'],

        'platform-main-module': ['angular', 'angularAMD'],
        'attribute-level-field-directives': ['angular', 'angularAMD'],

        'overlay': ['angular', 'angularAMD'],
        'ace': ['angularAMD'],
        'ui-ace':['angularAMD','ace'],
        'dndLists': ['angular','angularAMD'],
        "DlhSoft":  ['angular','angularAMD'],
    },
    // kick start application
    deps: ['app']
});
